spring:
  application:
    name: our-company-lunch-webflux
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/ourcompanylunchwebflux
    username: root
    password: a1234
logging:
  level:
    io.r2dbc.spi: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
